version: '2'

services:
    nginx:
        restart: always
        build:
            context: ../
            dockerfile: DockerfileNginx
        image: runspots_nginx
        container_name: runspots_nginx

    postgres:
        restart: always
        image: postgres:9.5
        volumes:
            - ../scripts/init-db-user.sh:/docker-entrypoint-initdb.d/init-db-user.sh
            - ../var/db/postgres:/var/lib/postgresql/data/
        env_file:
            - ../vars.env
        container_name: runspots_db

    redis:
        restart: always
        image: redis:latest
        volumes:
            - ../var/db/redis:/data
        container_name: runspots_rd

    rabbitmq:
        restart: always
        image: rabbitmq:latest
        volumes:
            - ../var/db/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@runspots_rq
        hostname: "runspots_rq"
        env_file:
            - ../vars.env
        container_name: runspots_rq

    web:
        restart: always
        build:
            context: ../
        image: runspots_web
        volumes:
            - ../:/srv/caffeine/project
        env_file:
            - ../vars.env
        container_name: runspots_web
        working_dir: "/srv/caffeine/project"
        command: scripts/docker_start.sh
