version: '2'

services:
    nginx:
        extends:
            file: base.yml
            service: nginx
        volumes_from:
            - web
        ports:
            - "80:80"
            - "443:443"
        links:
            - rabbitmq
            - redis
            - postgres
            - web

    postgres:
        extends:
            file: base.yml
            service: postgres
        ports:
            - "8013:5432"

    redis:
        extends:
            file: base.yml
            service: redis

    rabbitmq:
        extends:
            file: base.yml
            service: rabbitmq
        ports:
            - "8014:15672"

    web:
        extends:
            file: base.yml
            service: web
        ports:
            - "8015:8000"
            - "2767:22"
